In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
dataset = pd.read_csv('height_weight.csv')[['height','weight']]

In [6]:
dataset.head()

height  weight
0   71.74  259.88
1   71.00  186.73
2   63.83  172.17
3   67.74  174.66
4   67.28  169.20

## CoVariance

In [7]:
covariance = np.cov(dataset)    #here numpy has considered each value as different and computed it's covariance 
                                    # against all other values
print(covariance)

[[17698.3298  10886.7211  10191.5438  ...  9768.2288   6992.2231
   4852.1306 ]
 [10886.7211   6696.71645  6269.0941  ...  6008.7016   4301.10545
   2984.6767 ]
 [10191.5438   6269.0941   5868.7778  ...  5625.0128   4026.4561
   2794.0886 ]
 ...
 [ 9768.2288   6008.7016   5625.0128  ...  5391.3728   3859.2136
   2678.0336 ]
 [ 6992.2231   4301.10545  4026.4561  ...  3859.2136   2762.47445
   1916.9707 ]
 [ 4852.1306   2984.6767   2794.0886  ...  2678.0336   1916.9707
   1330.2482 ]]


In [8]:
covariance = np.cov(dataset.T) # rows * columns
print(covariance)

[[  18.60200779   78.50218098]
 [  78.50218098 1512.91208783]]


In [9]:
covariance = np.cov(dataset, rowvar= False) 
print(covariance)

[[  18.60200779   78.50218098]
 [  78.50218098 1512.91208783]]


In [10]:
covariance = dataset.cov()
print(covariance)

           height       weight
height  18.602008    78.502181
weight  78.502181  1512.912088


## Coorelation

In [12]:
corr = np.corrcoef(dataset.T)
print(corr)

[[1.         0.46794517]
 [0.46794517 1.        ]]


In [13]:
corr = dataset.corr()
print(corr)

          height    weight
height  1.000000  0.467945
weight  0.467945  1.000000
